version: "3.9"

services:
  app:
    build: .
    container_name: php_financas_app
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: financas
      DB_USER: postgres
      DB_PASSWORD: postgres
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: nacadroli@gmail.com
      SMTP_PASS: lfvo amnv kitd sbqe
      SMTP_FROM_EMAIL: nacadroli@gmail.com
      SMTP_FROM_NAME: Sistema Financeiro
      MAIL_TO: natan.acadroli@universo.univates.br
    volumes:
      - ./app:/var/www/html

  db:
    image: postgres:15
    container_name: php_financas_db
    restart: always
    environment:
      POSTGRES_DB: financas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
